spring.datasource.url=jdbc:postgresql://localhost:5432/daphne_db
spring.datasource.username=daphne_user
spring.datasource.password=changeme
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
